server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.0.88
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.0.88
ly:
  sms:
    accessKeyId: LTAIHv2WM1tnASwj # 你自己的accessKeyId
    accessKeySecret: lstAPClJ9gvK3tTs1VD20tnuNckeNp # 你自己的AccessKeySecret
    signName: 乐友商城 # 签名名称
    verifyCodeTemplate: SMS_168587437 # 模板名称