server:
  port: 8084
spring:
  application:
    name: page-service
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.0.88
    username: leyou
    password: leyou
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka